// Auto-generated by scripts/generate-clips.js — maps clip id → bundled asset.
// Edit by re-running `node scripts/generate-clips.js <video> --job <jobId>`.

export const CLIP_VIDEOS: Record<string, number> = {
  "job-001-01": require("../assets/clips/job-001-01.mp4"),
  "job-001-02": require("../assets/clips/job-001-02.mp4"),
  "job-001-03": require("../assets/clips/job-001-03.mp4"),
  "job-001-04": require("../assets/clips/job-001-04.mp4"),
};

export const CLIP_THUMBS: Record<string, number> = {
  "job-001-01": require("../assets/clips/thumbs/job-001-01.jpg"),
  "job-001-02": require("../assets/clips/thumbs/job-001-02.jpg"),
  "job-001-03": require("../assets/clips/thumbs/job-001-03.jpg"),
  "job-001-04": require("../assets/clips/thumbs/job-001-04.jpg"),
};
